services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://cv:cvpass@db:5432/cvdb
      - TRPC_ENDPOINT=http://web:3000/api/trpc
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  db:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=cv
      - POSTGRES_PASSWORD=cvpass
      - POSTGRES_DB=cvdb
    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data:
  uploads_data: